package com.reamicro.fix.ui

import android.content.Context
import androidx.annotation.StringRes
import com.reamicro.fix.R
import com.reamicro.fix.cloud.local.DAILY_LORE_DETAIL_KEY
import com.reamicro.fix.cloud.local.LocalTaskRecord
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Keys below are the existing on-disk/host protocol keys. Translate only their presentation:
 * never rename JSON keys, rewrite old records, or translate service-provided names and content.
 */
@StringRes
internal fun moduleDetailLabelResource(key: String): Int? = when (key) {
    "轶闻" -> R.string.detail_lore
    "出处" -> R.string.detail_source
    "类型" -> R.string.detail_type
    "等级" -> R.string.detail_level
    "正文" -> R.string.detail_body
    "奖励" -> R.string.detail_reward
    "阅历" -> R.string.detail_experience
    "彩筹" -> R.string.detail_tokens
    "期物" -> R.string.detail_item
    "开始时间" -> R.string.detail_start_time
    "结束时间" -> R.string.detail_end_time
    "领取时间" -> R.string.detail_claim_time
    "提示" -> R.string.detail_hint
    "事件", "事件详情" -> R.string.detail_events
    "收益" -> R.string.detail_profit
    "今日次数" -> R.string.detail_daily_count
    "今日累计" -> R.string.detail_daily_total
    "典当数量" -> R.string.detail_pawn_count
    "图书" -> R.string.field_books
    "城池" -> R.string.field_city
    "效果" -> R.string.detail_effect
    "新行商" -> R.string.detail_new_merchant
    "新行商结束时间" -> R.string.detail_new_merchant_end
    "新行商运签" -> R.string.detail_new_merchant_blessing
    "新行商运签效果" -> R.string.detail_new_merchant_blessing_effect
    "时长" -> R.string.detail_duration
    "本次祈愿" -> R.string.detail_wishes
    "本金" -> R.string.field_principal
    "状态" -> R.string.about_status
    "结算" -> R.string.detail_settlement
    "获得" -> R.string.detail_received
    "获得铜钱" -> R.string.detail_coins_received
    "行程" -> R.string.detail_trip
    "车马" -> R.string.field_transport
    "运签" -> R.string.field_blessing
    "运签效果" -> R.string.detail_blessing_effect
    "领取奖励" -> R.string.detail_reward_claim
    else -> null
}

internal fun moduleRecordDetailText(
    context: Context,
    accountId: String,
    record: LocalTaskRecord,
    taskTitle: String,
    resultLabel: String,
): String = formatModuleRecordDetails(
    accountId, record, taskTitle, resultLabel, context.resources.configuration.locales[0],
) { id, args ->
    if (args.isEmpty()) context.getString(id) else context.getString(id, *args)
}

/** Pure formatter so both language versions can be tested without a device or Android Context. */
internal fun formatModuleRecordDetails(
    accountId: String,
    record: LocalTaskRecord,
    taskTitle: String,
    resultLabel: String,
    locale: Locale,
    strings: (Int, Array<out Any>) -> String,
): String {
    fun text(@StringRes id: Int, vararg args: Any): String = strings(id, args)
    val detail = runCatching { JSONObject(record.detail) }.getOrNull()
    val lore = detail?.optJSONObject(DAILY_LORE_DETAIL_KEY)?.takeIf { record.taskType == "yeshe_checkin" }
    val fields = detail?.let { localTaskRecordDetailFields(record.taskType, it) }.orEmpty()
    return buildString {
        append(text(
            R.string.record_detail_header,
            SimpleDateFormat("MM-dd HH:mm:ss", locale).format(Date(record.at)),
            taskTitle, accountId, resultLabel,
        ))
        append("\n\n")
        append(record.message)
        fields.forEachIndexed { index, field ->
            append(if (index == 0) "\n\n" else "\n")
            val label = moduleDetailLabelResource(field.label)?.let { text(it) } ?: field.label
            val value = when {
                field.label == "类型" && lore?.optString("type") == "STORY" -> text(R.string.detail_story)
                field.label == "奖励" && field.value == "已领取" -> text(R.string.detail_claimed)
                field.label == "奖励" && field.value == "待领取" -> text(R.string.detail_unclaimed)
                field.label == "阅历" && lore != null -> text(R.string.detail_experience_value, lore.optString("exp"))
                field.label == "彩筹" && lore != null -> text(R.string.detail_tokens_value, lore.optString("gem"))
                // The final hint is generated by the legacy parser, not supplied by the server.
                field.label == "提示" && index == fields.lastIndex && lore == null &&
                    record.taskType == "yeshe_checkin" && !detail?.optString("轶闻").isNullOrBlank() -> text(R.string.detail_legacy_hint)
                else -> field.value
            }
            append(text(if (field.label == "正文") R.string.detail_body_line else R.string.detail_line, label, value))
        }
    }
}
