package com.reamicro.fix.tts

object ReadAloudIntents {
    const val MODULE_PACKAGE_NAME = "com.reamicro.fix"
    const val SERVICE_CLASS_NAME = "com.reamicro.fix.tts.ReadAloudService"
    const val COMMAND_RECEIVER_CLASS_NAME = "com.reamicro.fix.tts.ReadAloudCommandReceiver"
    const val COMMAND_ACTIVITY_CLASS_NAME = "com.reamicro.fix.tts.ReadAloudCommandActivity"
    const val HOST_PACKAGE_NAME = "app.zhendong.reamicro"

    const val ACTION_PREPARE = "com.reamicro.fix.READ_ALOUD_PREPARE"
    const val ACTION_APPEND = "com.reamicro.fix.READ_ALOUD_APPEND"
    const val ACTION_PLAY = "com.reamicro.fix.READ_ALOUD_PLAY"
    const val ACTION_PAUSE = "com.reamicro.fix.READ_ALOUD_PAUSE"
    const val ACTION_RESUME = "com.reamicro.fix.READ_ALOUD_RESUME"
    const val ACTION_STOP = "com.reamicro.fix.READ_ALOUD_STOP"
    const val ACTION_PREV = "com.reamicro.fix.READ_ALOUD_PREV"
    const val ACTION_NEXT = "com.reamicro.fix.READ_ALOUD_NEXT"
    const val ACTION_CURRENT = "com.reamicro.fix.READ_ALOUD_CURRENT"
    const val ACTION_CLEAR = "com.reamicro.fix.READ_ALOUD_CLEAR"
    const val ACTION_SYNC_PROGRESS = "com.reamicro.fix.READ_ALOUD_SYNC_PROGRESS"
    const val ACTION_CLEAR_PROGRESS = "com.reamicro.fix.READ_ALOUD_CLEAR_PROGRESS"

    const val EXTRA_SESSION_ID = "session_id"
    const val EXTRA_BOOK_KEY = "book_key"
    const val EXTRA_BOOK_TITLE = "book_title"
    const val EXTRA_COVER_URI = "cover_uri"
    const val EXTRA_SOURCE_JSON = "source_json"
    const val EXTRA_TOTAL_CHUNKS = "total_chunks"
    const val EXTRA_CHUNK_INDEX = "chunk_index"
    const val EXTRA_TEXTS = "texts"
    const val EXTRA_HIGHLIGHT_TEXTS = "highlight_texts"
    const val EXTRA_TITLES = "titles"
    const val EXTRA_CHAPTER_INDICES = "chapter_indices"
    const val EXTRA_START_CFIS = "start_cfis"
    const val EXTRA_END_CFIS = "end_cfis"
    const val EXTRA_TEXT = "text"
    const val EXTRA_HIGHLIGHT_TEXT = "highlight_text"
    const val EXTRA_CHAPTER_TITLE = "chapter_title"
    const val EXTRA_CHAPTER_INDEX = "chapter_index"
    const val EXTRA_PARAGRAPH_INDEX = "paragraph_index"
    const val EXTRA_START_CFI = "start_cfi"
    const val EXTRA_END_CFI = "end_cfi"
    const val EXTRA_PLAYING = "playing"
    const val EXTRA_PLAYBACK_STARTED = "playback_started"
    const val EXTRA_PROGRESS_RECORDABLE = "progress_recordable"
    const val EXTRA_PLAYBACK_ELAPSED_MS = "playback_elapsed_ms"
    const val EXTRA_RESTORED_PROGRESS = "restored_progress"
    const val EXTRA_IGNORE_AUDIO_FOCUS = "ignore_audio_focus"
    const val EXTRA_LYRICON_ENABLED = "lyricon_enabled"
    const val EXTRA_CLEAR_SESSION = "clear_session"
    const val EXTRA_AUTO_PLAY = "auto_play"
}
