package com.reamicro.fix.hook

fun main() {
    val titles = ReaderSearchPresentation.titles(
        listOf("第三卷 万物有终亡", "第626章 再遇拉德斯上尉"), "第626章 再遇拉德斯上尉",
    )
    check(titles.volume == "第三卷 万物有终亡")
    check(titles.chapter == "第626章 再遇拉德斯上尉")
    check(ReaderSearchPresentation.titles(listOf("第三卷 万物有终亡", "第626章 再遇拉德斯上尉")) == titles)
    check(ReaderSearchPresentation.titles(listOf("序 序异乡人的血宴", "第16章 函授教育入学邀请")).volume == "序 序异乡人的血宴")
    check(ReaderSearchPresentation.titles(listOf("第二部", "漫长的归途")).volume == "第二部")
    check(ReaderSearchPresentation.titles(listOf("第16章 函授教育入学邀请")).volume.isEmpty())
    check(ReaderSearchPresentation.titles(listOf("第16章 函授教育入学邀请")).chapter == "第16章 函授教育入学邀请")
    check(ReaderSearchPresentation.titles(listOf("OEBPS/Text/Chapter0017.xhtml")).chapter == "未命名章节")
    check(ReaderSearchPresentation.titles(listOf("Chapter0017"), filename = "Chapter0017").chapter == "未命名章节")
    check(ReaderSearchPresentation.titles(emptyList()).chapter == "未命名章节")
    val afterword = ReaderSearchPresentation.titles(listOf("隐杀丨后篇丨", "第3章 爸爸是医生"))
    check(afterword.volume == "隐杀丨后篇丨" && afterword.chapter == "第3章 爸爸是医生")
    check(ReaderSearchPresentation.titles(listOf("第八卷丨往日之扉丨", "第449章 生气")).volume == "第八卷丨往日之扉丨")
    check(ReaderSearchPresentation.titles(listOf("任意名字", "没有章号的标题")).volume == "任意名字")
    // 单个目录节点里的空格、章号、竖线都不是结构，不能猜着拆开。
    val unsplit = "第三卷 往事丨第3章 爸爸是医生"
    check(ReaderSearchPresentation.titles(listOf(unsplit)) == ReaderSearchPresentation.Titles("", unsplit))
    check(ReaderSearchPresentation.titles(emptyList(), unsplit) == ReaderSearchPresentation.Titles("", unsplit))

    val sections = ReaderSearchPresentation.sections(listOf("序", "第三卷", "第三卷", "第四卷", "", "第五卷"))
    check(sections.map { it.volume } == listOf("序", "第三卷", "第四卷", "", "第五卷"))
    check(sections.flatMap { it.start until it.endExclusive } == (0..5).toList())
    check(sections[1].start == 1 && sections[1].endExclusive == 3)
    check(ReaderSearchPresentation.sections(emptyList()).isEmpty())
    check(ReaderSearchPresentation.sections(listOf("一", "二", "一")).size == 3)
    // 流式追加同卷结果时，分组起点必须保持不变，点击仍使用原始结果序号。
    check(ReaderSearchPresentation.sections(listOf("一", "一")) == listOf(ReaderSearchPresentation.Section("一", 0, 2)))
    check(ReaderSearchPresentation.sections(listOf("一", "一", "一")).single().start == 0)
    check(ReaderSearchPresentation.listIndex(listOf("一", "一", "二", "二"), 0) == 1)
    check(ReaderSearchPresentation.listIndex(listOf("一", "一", "二", "二"), 2) == 4)
    check(ReaderSearchPresentation.listIndex(listOf("一", "一", "二", "二"), 3) == 5)
    check(ReaderSearchPresentation.listIndex(emptyList(), 0) == null)
    check(ReaderSearchPresentation.listIndex(listOf("一"), -1) == null)

    fun snippet(text: String, keyword: String, radius: Int) = text.indexOf(keyword).let {
        searchSnippet(text, it, it + keyword.length, radius)
    }
    val normalized = snippet("开头\n\t多个   空白 魔法  出现\n\n结尾", "魔法", 30)
    check(normalized.text == "开头 多个 空白 魔法 出现 结尾")
    check(normalized.text.substring(normalized.matchStart, normalized.matchEnd) == "魔法")
    check(snippet("魔法就在开头", "魔法", 19).matchStart == 0)
    val trailing = snippet("前文 魔法", "魔法", 19)
    check(trailing.matchEnd == trailing.text.length)
    val expanded = snippet("甲".repeat(100) + "魔法" + "乙".repeat(100), "魔法", 19)
    check(expanded.text.length == 42)
    check(expanded.text.substring(expanded.matchStart, expanded.matchEnd) == "魔法")
    val spaces = snippet("intro a  b ending", "a  b", 35)
    check(spaces.text.substring(spaces.matchStart, spaces.matchEnd) == "a b")
    check(ReaderSearchPresentation.status("其他", "魔法", false, 37, null) == null)
    check(ReaderSearchPresentation.status("魔法", "魔法", false, 37, null) == "共找到 37 处")
    val position = ReaderSearchListPosition("book-a", "魔法", 15, 29)
    check(position.forSearch("book-a", "魔法") == position)
    check(position.forSearch("book-b", "魔法") == null)
    check(position.forSearch("book-a", "魔") == null)
    val bounds = ReaderSearchBarPlacement.bounds(400, 800, 300, 48, 0, 24, 0, 20, 16f)
    val placement = ReaderSearchBarPlacement()
    check(placement.position(bounds) == ReaderSearchBarPlacement.Point(50f, 732f))
    val moved = placement.moveBy(100f, -200f, bounds)
    check(moved.x == bounds.right && moved.y == 532f)
    check(placement.position(bounds) == moved)
    // 新搜索销毁旧悬浮栏并创建新栏，默认位置不继承上一轮拖动。
    check(ReaderSearchBarPlacement().position(bounds) == ReaderSearchBarPlacement.Point(50f, 732f))
    val edge = ReaderSearchBarPlacement.bounds(400, 800, 300, 48, 0, 24, 0, 0, 16f)
    check(ReaderSearchBarPlacement().position(edge).y + 48 == 800f)
    val ime = ReaderSearchBarPlacement.bounds(400, 800, 300, 48, 0, 24, 0, 320, 16f)
    check(ReaderSearchBarPlacement().position(ime).y + 48 == 480f)

    val request = ReaderSearchRequest(1, 4, 50)
    check(request.acceptsSearch(1, 4))
    check(!request.acceptsSearch(2, 4) && !request.acceptsSearch(1, 5))
    // 列表关闭、重开不影响搜索任务；旧窗口本身仍不能接收新窗口更新。
    check(!request.accepts(1, 4, 0, false) && request.acceptsSearch(1, 4))
    check(!request.accepts(1, 4, 60, true) && request.accepts(1, 4, 50, true))
    val queue = mutableListOf<Runnable>()
    val consumed = mutableListOf<Int>()
    val updates = LatestSearchUpdate<Int>({ queue += it }, { consumed += it })
    repeat(2000) { updates.offer(it) }
    check(queue.size == 1)
    queue.removeAt(0).run()
    check(consumed == listOf(1999))
    updates.offer(2000)
    check(queue.size == 1)
    queue.removeAt(0).run()
    check(consumed == listOf(1999, 2000))
    val budget = SearchIndexBudget(1024)
    check(budget.retain(512) && budget.retain(512))
    check(!budget.retain(1) && !budget.cacheable && !budget.retain(0))
    check(!SearchIndexBudget(1024).retain(Long.MAX_VALUE))
    println("Search regression passed: presentation, selection, bottom edge, detached search, bounded updates and index memory")
}
