package com.reamicro.fix.core

/**
 * 宿主与框架的类名常量集中定义。
 *
 * 本模块所有功能都靠反射调用宿主类，宿主一升级、类名一变，功能就静默失效。
 * 此前这些类名以字符串字面量散落在二十多个文件里，排查一次回归要满仓 grep 且容易漏。
 *
 * 约定：任何宿主类名（`app.zhendong.*`）或框架类名只在这里出现一次，各 hook 通过
 * 引用本对象的常量拿到类名。宿主升级时，改这一个文件即可。
 */
object HostClasses {

    /** Kotlin 运行时。 */
    object Kotlin {
        const val DEFAULT_CONSTRUCTOR_MARKER = "kotlin.jvm.internal.DefaultConstructorMarker"
        const val FUNCTION0 = "kotlin.jvm.functions.Function0"
        const val FUNCTION1 = "kotlin.jvm.functions.Function1"
        const val FUNCTION2 = "kotlin.jvm.functions.Function2"
        const val FUNCTION3 = "kotlin.jvm.functions.Function3"
        const val KOTLIN_CONTINUATION = "kotlin.coroutines.Continuation"
        const val KOTLIN_COROUTINE_SINGLETONS = "kotlin.coroutines.intrinsics.CoroutineSingletons"
        const val KOTLIN_EMPTY_COROUTINE_CONTEXT = "kotlin.coroutines.EmptyCoroutineContext"
        const val KOTLIN_INTRINSICS = "kotlin.coroutines.intrinsics.IntrinsicsKt"
        const val KOTLIN_PAIR = "kotlin.Pair"
        const val KOTLIN_REFLECTION = "kotlin.jvm.internal.Reflection"
        const val KOTLIN_RESULT = "kotlin.Result"
        const val KOTLIN_RESULT_KT = "kotlin.ResultKt"
        const val KOTLIN_UNIT = "kotlin.Unit"
    }

    /** Compose 运行时（含 compose-resources）。 */
    object Compose {
        const val ALIGNMENT = "androidx.compose.ui.Alignment"
        const val ALPHA_KT = "androidx.compose.ui.draw.AlphaKt"
        const val ANDROID_CANVAS_KT = "androidx.compose.ui.graphics.AndroidCanvas_androidKt"
        const val ANDROID_VIEW_KT = "androidx.compose.ui.viewinterop.AndroidView_androidKt"
        const val ANIMATED_VISIBILITY_KT = "androidx.compose.animation.AnimatedVisibilityKt"
        const val ANNOTATED_STRING = "androidx.compose.ui.text.AnnotatedString"
        const val ARRANGEMENT = "androidx.compose.foundation.layout.Arrangement"
        const val ARROW_BACK_ICON = "androidx.compose.material.icons.automirrored.outlined.ArrowBackKt"
        const val BACKGROUND_KT = "androidx.compose.foundation.BackgroundKt"
        const val BASIC_TEXT = "androidx.compose.foundation.text.BasicTextKt"
        const val BORDER_KT = "androidx.compose.foundation.BorderKt"
        const val BOX_KT = "androidx.compose.foundation.layout.BoxKt"
        const val BRUSH_COMPANION = "androidx.compose.ui.graphics.Brush"
        const val BRUSH_KT = "androidx.compose.ui.graphics.BrushKt"
        const val CLICKABLE_KT = "androidx.compose.foundation.ClickableKt"
        const val CLIP_KT = "androidx.compose.ui.draw.ClipKt"
        const val COLOR = "androidx.compose.ui.graphics.Color"
        const val COLOR_KT = "androidx.compose.ui.graphics.ColorKt"
        const val COLOR_SCHEME = "androidx.compose.material3.ColorScheme"
        const val COLUMN_KT = "androidx.compose.foundation.layout.ColumnKt"
        const val COMPOSABLE_LAMBDA_KT = "androidx.compose.runtime.internal.ComposableLambdaKt"
        const val COMPOSER = "androidx.compose.runtime.Composer"
        const val COMPOSE_PLACEHOLDER = "androidx.compose.ui.text.Placeholder"
        const val COMPOSE_STATE = "androidx.compose.runtime.State"
        const val CONTENT_COPY_ICON = "androidx.compose.material.icons.outlined.ContentCopyKt"
        const val DARK_MODE_ICON = "androidx.compose.material.icons.outlined.DarkModeKt"
        const val DICTIONARY_ICON_AUTO_STORIES = "androidx.compose.material.icons.outlined.AutoStoriesKt"
        const val DICTIONARY_ICON_BOOK = "androidx.compose.material.icons.outlined.BookKt"
        const val DICTIONARY_ICON_MENU_BOOK = "androidx.compose.material.icons.outlined.MenuBookKt"
        const val DICTIONARY_ICON_TRANSLATE = "androidx.compose.material.icons.outlined.TranslateKt"
        const val DRAW_MODIFIER_KT = "androidx.compose.ui.draw.DrawModifierKt"
        const val EDIT_ICON = "androidx.compose.material.icons.outlined.EditKt"
        const val FLOW_LAYOUT_KT = "androidx.compose.foundation.layout.FlowLayoutKt"
        const val FONT_FAMILY = "androidx.compose.ui.text.font.FontFamily"
        const val FONT_FAMILY_KT = "androidx.compose.ui.text.font.FontFamilyKt"
        const val FONT_WEIGHT = "androidx.compose.ui.text.font.FontWeight"
        const val FOUNDATION_SHAPE_KT = "androidx.compose.foundation.shape.RoundedCornerShapeKt"
        const val HIGHLIGHT_ICON_BORDER_COLOR = "androidx.compose.material.icons.outlined.BorderColorKt"
        const val HIGHLIGHT_ICON_FORMAT_COLOR_FILL = "androidx.compose.material.icons.outlined.FormatColorFillKt"
        const val HIGHLIGHT_ICON_MODE_EDIT = "androidx.compose.material.icons.outlined.ModeEditKt"
        const val ICON_KT = "androidx.compose.material3.IconKt"
        const val IMAGE_VECTOR = "androidx.compose.ui.graphics.vector.ImageVector"
        const val INLINE_CONTENT_ANNOTATION_TAG = "androidx.compose.foundation.text.inlineContent"
        const val LAZY_DSL_KT = "androidx.compose.foundation.lazy.LazyDslKt"
        const val LAZY_LIST_SCOPE = "androidx.compose.foundation.lazy.LazyListScope"
        const val LIGHT_MODE_ICON = "androidx.compose.material.icons.outlined.LightModeKt"
        const val LIST_ITEM_DEFAULTS = "androidx.compose.material3.ListItemDefaults"
        const val LIST_ITEM_KT = "androidx.compose.material3.ListItemKt"
        const val MATERIAL_THEME = "androidx.compose.material3.MaterialTheme"
        const val MODIFIER = "androidx.compose.ui.Modifier"
        const val MUTABLE_STATE = "androidx.compose.runtime.MutableState"
        const val NAVIGATE_NEXT_ICON = "androidx.compose.material.icons.automirrored.filled.NavigateNextKt"
        const val PADDING_KT = "androidx.compose.foundation.layout.PaddingKt"
        const val PADDING_VALUES = "androidx.compose.foundation.layout.PaddingValues"
        const val PLACEHOLDER_VERTICAL_ALIGN = "androidx.compose.ui.text.PlaceholderVerticalAlign"
        const val READ_ALOUD_ICON_RECORD_VOICE_OVER = "androidx.compose.material.icons.outlined.RecordVoiceOverKt"
        const val READ_ALOUD_ICON_VOLUME_UP = "androidx.compose.material.icons.outlined.VolumeUpKt"
        const val RECTANGLE_SHAPE_KT = "androidx.compose.ui.graphics.RectangleShapeKt"
        const val ROW_KT = "androidx.compose.foundation.layout.RowKt"
        const val ROW_SCOPE = "androidx.compose.foundation.layout.RowScope"
        const val SCAFFOLD_KT = "androidx.compose.material3.ScaffoldKt"
        const val SCALE_KT = "androidx.compose.ui.draw.ScaleKt"
        const val SCROLL_KT = "androidx.compose.foundation.ScrollKt"
        const val SEARCH_ICON = "androidx.compose.material.icons.outlined.SearchKt"
        const val SIZE_KT = "androidx.compose.foundation.layout.SizeKt"
        const val SNAPSHOT_STATE_KT = "androidx.compose.runtime.SnapshotStateKt__SnapshotStateKt"
        const val SOLID_COLOR = "androidx.compose.ui.graphics.SolidColor"
        const val SPACER_KT = "androidx.compose.foundation.layout.SpacerKt"
        const val SPAN_STYLE = "androidx.compose.ui.text.SpanStyle"
        const val STRING_ANNOTATION = "androidx.compose.ui.text.StringAnnotation"
        const val STRING_RESOURCES = "org.jetbrains.compose.resources.StringResourcesKt"
        const val SWITCH_DEFAULTS = "androidx.compose.material3.SwitchDefaults"
        const val SWITCH_KT = "androidx.compose.material3.SwitchKt"
        const val TEXT_KT = "androidx.compose.material3.TextKt"
        const val TEXT_OVERFLOW = "androidx.compose.ui.text.style.TextOverflow"
        const val TEXT_STYLE = "androidx.compose.ui.text.TextStyle"
        const val TEXT_UNIT_KT = "androidx.compose.ui.unit.TextUnitKt"
        const val TOP_APP_BAR_DEFAULTS = "androidx.compose.material3.TopAppBarDefaults"
        const val VECTOR_KT = "androidx.compose.ui.graphics.vector.VectorKt"
        const val WINDOW_INSETS = "androidx.compose.foundation.layout.WindowInsets"
        const val WINDOW_INSETS_KT = "androidx.compose.foundation.layout.WindowInsetsKt"
    }

    /** AndroidX（非 Compose）。 */
    object AndroidX {
        const val BACK_HANDLER_KT = "androidx.activity.compose.BackHandlerKt"
        const val LOAD_STATES = "androidx.paging.LoadStates"
        const val NAVIGATION_EVENT_HANDLER_KT = "androidx.navigationevent.compose.NavigationEventHandlerKt"
        const val NAV_BACK_STACK_ENTRY_KT = "androidx.navigation.NavBackStackEntryKt"
        const val NAV_CONTROLLER = "androidx.navigation.NavController"
        const val PAGING_DATA = "androidx.paging.PagingData"
        const val REMEMBER_NAVIGATION_EVENT_STATE_KT = "androidx.navigationevent.compose.RememberNavigationEventStateKt"
    }

    /** 阅微宿主。 */
    object Host {
        const val ABOUT_SCREEN = "app.zhendong.reamicro.ui.setting.AboutScreenKt"
        const val ACCOUNT_SECURITY_SCREEN = "app.zhendong.reamicro.ui.setting.AccountSecurityScreenKt"
        const val ALIYUN_ICON = "app.zhendong.reamicro.arch.icons.colored.AliyunKt"
        const val ANDROID_OS_ICON = "app.zhendong.reamicro.arch.icons.colored.AndroidOsKt"
        const val APP_ABOUT = "app.zhendong.reamicro.ui.setting.components.AppAboutKt"
        const val APP_KT = "app.zhendong.reamicro.AppKt"
        const val APP_TOP_BAR = "app.zhendong.reamicro.arch.components.AppTopBarKt"
        const val AUTH_CARD = "app.zhendong.reamicro.ui.backup.components.AuthCardKt"
        const val BACKUP_TYPE = "app.zhendong.reamicro.constants.BackupType"
        const val BAIDU_ACCOUNT_SCREEN = "app.zhendong.reamicro.ui.storage.baidu.BaiduNetDiskAccountScreenKt"
        const val BAIDU_ICON = "app.zhendong.reamicro.arch.icons.colored.BaiduNetdiskKt"
        const val BAIDU_VIEW_MODEL = "app.zhendong.reamicro.ui.storage.baidu.BaiduNetDiskViewModel"
        const val BOOK = "app.zhendong.reamicro.data.db.entity.Book"
        const val BOOKMARK = "app.zhendong.reamicro.data.reader.Bookmark"
        const val BOOKSHELF_REPOSITORY = "app.zhendong.reamicro.repository.BookshelfRepository"
        const val BOOKSHELF_SCREEN = "app.zhendong.reamicro.ui.home.BookshelfScreenKt"
        const val BOOK_BACKUP_SCREEN = "app.zhendong.reamicro.ui.backup.BookBackupScreenKt"
        const val BOOK_BACKUP_VIEW_MODEL = "app.zhendong.reamicro.ui.backup.BookBackupViewModel"
        const val BOOK_DETAILS_VIEW_MODEL = "app.zhendong.reamicro.ui.book.BookDetailsViewModel"
        const val BOOK_LIBRARY_SHEET = "app.zhendong.reamicro.ui.home.components.BookLibrarySheetKt"
        const val BOOK_LOCAL_SHEET = "app.zhendong.reamicro.ui.home.components.BookLocalSheetKt"
        const val BOOK_OVERVIEW_ITEMS = "app.zhendong.reamicro.ui.home.components.BookOverviewItemsKt"
        const val BOOK_OVERVIEW_VIEW_MODEL = "app.zhendong.reamicro.ui.home.BookOverviewViewModel"
        const val BOOK_PUBLISH_VIEW_MODEL = "app.zhendong.reamicro.ui.book.BookPublishViewModel"
        const val BOOK_ROW_INFO = "app.zhendong.reamicro.ui.storage.components.BookRowInfoKt"
        const val CACHED = "app.zhendong.reamicro.repository.core.Cached"
        const val CATALOG_CHAPTER_ITEM = "app.zhendong.reamicro.ui.reader.CatalogChapterItem"
        const val CLOUD_BOOK = "app.zhendong.reamicro.data.storage.CloudBook"
        const val CLOUD_BOOK_LIST = "app.zhendong.reamicro.ui.storage.components.CloudBookListKt"
        const val CLOUD_FOLDER = "app.zhendong.reamicro.data.storage.CloudFolder"
        const val CLOUD_STORAGE_REPOSITORY = "app.zhendong.reamicro.repository.storage.CloudStorageRepository"
        const val CLOUD_STORAGE_SCREEN = "app.zhendong.reamicro.ui.storage.CloudStorageScreenKt"
        const val CLOUD_STORAGE_UI_EVENT = "app.zhendong.reamicro.ui.storage.CloudStorageUIEvent"
        const val CLOUD_STORAGE_UI_STATE = "app.zhendong.reamicro.ui.storage.CloudStorageUiState"
        const val CLOUD_STORAGE_VIEW_MODEL = "app.zhendong.reamicro.ui.storage.CloudStorageViewModel"
        const val CLOUD_TREE = "app.zhendong.reamicro.ui.storage.components.CloudTreeKt"
        const val CLOUD_USER_INFO = "app.zhendong.reamicro.data.storage.CloudUserInfo"
        const val DIR = "app.zhendong.reamicro.data.third.Dir"
        const val DIVIDER_KT = "app.zhendong.reamicro.arch.components.DividerKt"
        const val DRIVE_CARD = "app.zhendong.reamicro.ui.backup.components.DriveCardKt"
        const val DYNAMIC_THEME_CONTENT_KT = "app.zhendong.reamicro.ui.reader.theme.DynamicThemeContentKt"
        const val ENVELOPE_KT = "app.zhendong.reamicro.data.res.EnvelopeKt"
        const val EPUB_CONTAINER_KT = "app.zhendong.reamicro.ui.reader.components.EpubContainerKt"
        const val EPUB_FILE_MANAGER = "app.zhendong.reamicro.arch.EpubFileManager"
        const val EPUB_PAGE = "app.zhendong.reamicro.data.epub.EpubPage"
        const val FILE_FOLDER_ICON = "app.zhendong.reamicro.arch.icons.colored.FileFolderKt"
        const val FILE_SOURCE = "app.zhendong.reamicro.arch.FileSource"
        const val FOOTER = "app.zhendong.reamicro.arch.components.item.FooterKt"
        const val HOME_SCREEN = "app.zhendong.reamicro.ui.home.HomeScreenKt"
        const val HOME_SEARCH_BAR = "app.zhendong.reamicro.ui.home.components.HomeSearchBarKt"
        const val HOME_VIEW_MODEL = "app.zhendong.reamicro.ui.home.HomeViewModel"
        const val HOST_PACKAGE_NAME = "app.zhendong.reamicro"
        const val HOST_TEXT_STYLE_KT = "app.zhendong.reamicro.arch.theme.TextStyleKt"
        const val HOST_USER = "app.zhendong.reamicro.data.db.entity.User"
        const val HOST_USER_DAO = "app.zhendong.reamicro.data.db.dao.UserDao"
        const val INTENT_RECEIVER = "app.zhendong.reamicro.arch.IntentReceiver"
        const val JUSTIFY_TEXT = "app.zhendong.reamicro.arch.components.JustifyText_androidKt"
        const val LOCAL_STORAGE_CARD = "app.zhendong.reamicro.ui.backup.components.LocalStorageCardKt"
        const val MAIN_ACTIVITY = "app.zhendong.reamicro.MainActivity"
        const val MARK = "app.zhendong.reamicro.data.db.entity.Mark"
        const val MATERIAL_SLIDER_DEFAULTS = "app.zhendong.reamicro.arch.components.slider.MaterialSliderDefaults"
        const val NAV_CONTROLLER_HOLDER = "app.zhendong.reamicro.arch.components.NavControllerHolder"
        const val NAV_GRAPH_SCOPE = "app.zhendong.reamicro.NavGraphScope"
        const val NOT_AUTH = "app.zhendong.reamicro.ui.storage.components.NotAuthKt"
        const val POST_USER_BOOK_REQ = "app.zhendong.reamicro.data.res.book.PostUserBookReq"
        const val PREF_KEYS = "app.zhendong.reamicro.constants.PrefKeys"
        const val PROFILE_SCREEN = "app.zhendong.reamicro.ui.profile.ProfileScreenKt"
        const val READER_BOTTOM_BAR = "app.zhendong.reamicro.ui.reader.components.ReaderBottomBarKt"
        const val READER_CATALOG = "app.zhendong.reamicro.ui.reader.compose.ReaderCatalogKt"
        const val READER_FAMILY_BUILD_IN = "app.zhendong.reamicro.ui.reader.compose.ReaderFamilyBuildInKt"
        const val READER_FAMILY_EPUB = "app.zhendong.reamicro.ui.reader.compose.ReaderFamilyEpubKt"
        const val READER_FAMILY_USER = "app.zhendong.reamicro.ui.reader.compose.ReaderFamilyUserKt"
        const val READER_HIGHLIGHT_SCREEN = "app.zhendong.reamicro.ui.reader.compose.ReaderHighlightScreenKt"
        const val READER_SCREEN_KT = "app.zhendong.reamicro.ui.reader.ReaderScreenKt"
        const val READER_SETTINGS = "app.zhendong.reamicro.ui.reader.compose.ReaderMoreSettingScreenKt"
        const val READER_SHARED_STATE = "app.zhendong.reamicro.ui.reader.components.ReaderSharedState"
        const val READER_THEMES_KT = "app.zhendong.reamicro.ui.reader.compose.ReaderThemesKt"
        const val READER_TYPE_SETTING = "app.zhendong.reamicro.ui.reader.compose.ReaderTypeSettingKt"
        const val READER_UI_INTENT = "app.zhendong.reamicro.ui.reader.ReaderUiIntent"
        const val READER_VIEW_MODEL = "app.zhendong.reamicro.ui.reader.ReaderViewModel"
        const val SCROLL_PAGER_KT = "app.zhendong.reamicro.ui.reader.components.ScrollPagerKt"
        const val SESSION = "app.zhendong.reamicro.repository.core.Session"
        const val SETTINGS_SCREEN = "app.zhendong.reamicro.ui.setting.SettingsScreenKt"
        const val SHAPE_KT = "app.zhendong.reamicro.arch.components.ShapeKt"
        const val SLIDER_BRUSH_COLOR = "app.zhendong.reamicro.arch.components.slider.SliderBrushColor"
        const val TAP_GESTURES_BOX = "app.zhendong.reamicro.ui.reader.components.TapGesturesBoxKt"
        const val THEME_KT = "app.zhendong.reamicro.arch.theme.ThemeKt"
        const val THIRD_PARTY = "app.zhendong.reamicro.data.search.ThirdParty"
        const val THIRD_PARTY_BOOK = "app.zhendong.reamicro.data.search.ThirdPartyBook"
        const val THIRD_PARTY_KEYS = "app.zhendong.reamicro.data.third.ThirdPartyKeys"
        const val TIME_EXT_KT = "app.zhendong.reamicro.arch.extensions.TimeExtKt"
        const val TYPE_SETTING_SLIDER = "app.zhendong.reamicro.ui.reader.components.TypeSettingSliderKt"
        const val UI_SHEET_STATUS = "app.zhendong.reamicro.ui.reader.UiSheetStatus"
        const val UI_STATUS = "app.zhendong.reamicro.ui.reader.UiStatus"
        const val UNIT_EXT_KT = "app.zhendong.reamicro.arch.extensions.UnitExtKt"
        const val USER_REPOSITORY = "app.zhendong.reamicro.repository.UserRepository"
        const val USER_STORAGE = "app.zhendong.reamicro.arch.fs.UserStorage"
        const val WINDOW_INSETS_EXT_ANDROID_KT = "app.zhendong.reamicro.ui.insets.WindowInsetsExt_androidKt"
        const val WORKER_MANAGER = "app.zhendong.reamicro.arch.WorkerManager"
        const val WORK_HANDLE = "app.zhendong.reamicro.arch.WorkHandle"
        const val WORK_STATE = "app.zhendong.reamicro.arch.WorkState"
        const val WORK_STATUS = "app.zhendong.reamicro.arch.WorkStatus"
        const val WORK_TRACKER = "app.zhendong.reamicro.arch.WorkTracker"
        const val Y115_ACCOUNT_SCREEN = "app.zhendong.reamicro.ui.storage.c115.Y115NetDiskAccountScreenKt"
        const val Y115_VIEW_MODEL = "app.zhendong.reamicro.ui.storage.c115.Y115NetDiskViewModel"
        const val YUN115_ICON = "app.zhendong.reamicro.arch.icons.colored.Yun115Kt"
    }

    /** 宿主 EPUB 引擎。 */
    object Epub {
        const val ANNOTATED_STRING_EXT = "org.epub.utils.AnnotatedStringExtKt"
        const val COMMENT_ANNOTATION = "org.epub.ui.CommentAnnotation"
        const val CONTENT_DOM = "org.epub.html.node.ContentDom"
        const val EPUB_CFI = "org.epub.html.EpubCFI"
        const val FONT_PROVIDER = "org.epub.FontProvider"
        const val HTML_DOCUMENT = "org.epub.html.HtmlDocument"
        const val IMAGE_PLACEHOLDER = "org.epub.html.ImagePlaceholder"
        const val OPF = "org.epub.structure.opf.Opf"
        const val UI_EPUB_WINDOW = "org.epub.UIEpubWindow"
    }

    /** 宿主内置的第三方库。 */
    object ThirdParty {
        const val OKHTTP_ANDROID10_PLATFORM = "okhttp3.internal.platform.Android10Platform"
        const val OKHTTP_ANDROID_PLATFORM = "okhttp3.internal.platform.AndroidPlatform"
        const val OKHTTP_CLIENT = "okhttp3.OkHttpClient"
        const val OKHTTP_MEDIA_TYPE = "okhttp3.MediaType"
        const val OKHTTP_PLATFORM = "okhttp3.internal.platform.Platform"
        const val OKHTTP_REQUEST = "okhttp3.Request"
        const val OKHTTP_REQUEST_BODY = "okhttp3.RequestBody"
        const val OKIO_PATH = "okio.Path"
    }
}
